name: jorgelima
favicon: null
layout_spectrum: 0.24995
typography_spectrum: 0.10359846404753625
title: 'Photographer '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#cfcfcf'
    - '#9f9f9f'
    - '#5f5f5f'
  brandStrength: 1
  lightness: 1
  saturation: 0.3147871738765389
  rhythmicContrast: 1
purpose: []
